#!/bin/bash

command -v rustfmt >/dev/null 2>&1 || { echo >&2 "Please install Rustfmt"; exit 1; }

HAS_ISSUES=0

for file in $(git diff --name-only --staged -- **/*.rs); do
    FMT_RESULT="$(rustfmt --check $file 2>/dev/null || true)"
    if [ "$FMT_RESULT" != "" ]; then
        printf "\n - $file"
        HAS_ISSUES=1
    fi
done

if [ $HAS_ISSUES -eq 0 ]; then
    exit 0
fi

printf "\n\n /!\ Your code has formatting issues in files listed above. Format your code with rustfmt."
exit 1