repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
        args:
          [
            "--workspace",
            "--all-targets",
            "--all-features",
            "--",
            # "-D",
            # "warnings",
          ]
      - id: cargo-check
        args: ["--workspace", "--all-targets", "--all-features"]
