[package]
name = "hyllar-indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
sdk = { path = "../../../contract-sdk", package="hyle-contract-sdk" }
hyllar = { path = "../contract", package="hyllar" }
hyle = { path = "../../..", package="hyle" }
anyhow = "1.0.89"
tracing = "0.1.41"
tokio = { version = "1", features = ["full"] }
