global:
  scrape_interval: 15s # Intervalle de scrape par défaut

scrape_configs:
  - job_name: "local-metrics"
    metrics_path: "/v1/metrics"
    scrape_interval: 1s # Intervalle spécifique pour ce job
    static_configs:
      - targets: ["host.docker.internal:4321"]
        labels:
          node: "hyle1"
      - targets: ["host.docker.internal:4322"]
        labels:
          node: "hyle2"
