FROM rust:alpine AS builder
RUN apk add gcc musl-dev g++
RUN cargo install risc0-r0vm

FROM alpine:latest
COPY --from=builder /usr/local/cargo/bin/r0vm /usr/local/bin/r0vm

# installing Barrenteberg CLI
RUN apk add --no-cache curl bash
ENV SHELL=/bin/bash
RUN curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/master/barretenberg/cpp/installation/install | bash
ENV PATH="/root/.bb:$PATH"
RUN bbup -v 0.41.0


