[package]
name = "hyfi-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.1", default-features = false, features = ['std'] }
sdk = { path = "../../../contract-sdk", package="hyle-contract-sdk" }
hyfi = { path = "../contract" }
