[package]
name = "hydentity-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "hydentity-guest"
test = false

[dependencies]
sdk = { path = "../../../contract-sdk", package = "hyle-contract-sdk", features = [
    "risc0",
] }
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
hydentity = { path = "../contract" }
