services:
  hyle:
    build: ./..
    privileged: true
    ports:
      - "4321:4321"
    volumes:
      - /tmp/hyle-container-data:/hyle/data
    network_mode: host
      
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"  # Port pour accéder à l'interface de Prometheus
    network_mode: host
    depends_on:
      - hyle

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"  # Port pour accéder à l'interface de Grafana
    environment:
      - GF_SECURITY_ALLOW_ANONYMOUS_ACCESS=true
    volumes:
      - ./observability/grafana-datasources:/etc/grafana/provisioning/datasources  # Montée de volume pour la source de données
    network_mode: host
    depends_on:
      - prometheus
