services:
  hyle1:
    build: ./..
    privileged: true
    network_mode: host
    environment:
      - HYLE_ID=leader-1
      - HYLE_REST=localhost:4001
      - HYLE_HOST=localhost:1001
      - HYLE_DA_ADDRESS=localhost:4141
      - HYLE_TCP_SERVER_ADDRESS=localhost:1414
      - RUST_LOG=debug
      - HYLE_CONSENSUS__SLOT_DURATION=3000
  hyle2:
    build: ./..
    privileged: true
    environment:
      - HYLE_ID=hyle2
      - HYLE_PEERS=localhost:1001
      - HYLE_REST=localhost:4002
      - HYLE_HOST=localhost:1002
      - HYLE_DA_ADDRESS=localhost:4142
      - HYLE_TCP_SERVER_ADDRESS=localhost:2414
      - RUST_LOG=debug
      - HYLE_CONSENSUS__SLOT_DURATION=3000
    network_mode: host
    depends_on:
      - hyle1
  hyle3:
    build: ./..
    privileged: true
    environment:
      - HYLE_ID=hyle3
      - HYLE_PEERS=localhost:1001,localhost:1002
      - HYLE_REST=localhost:4003
      - HYLE_HOST=localhost:1003
      - RUST_LOG=debug
      - HYLE_DA_ADDRESS=localhost:4143
      - HYLE_TCP_SERVER_ADDRESS=localhost:3414
      - HYLE_CONSENSUS__SLOT_DURATION=3000
    network_mode: host
    depends_on:
      - hyle1
  hyle4:
    build: ./..
    privileged: true
    environment:
      - HYLE_ID=hyle4
      - HYLE_PEERS=localhost:1001,localhost:1002,localhost:1003
      - HYLE_REST=localhost:4004
      - HYLE_HOST=localhost:1004
      - RUST_LOG=debug
      - HYLE_DA_ADDRESS=localhost:4144
      - HYLE_CONSENSUS__SLOT_DURATION=3000
    network_mode: host
    depends_on:
      - hyle1

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090" # Port pour accéder à l'interface de Prometheus
    network_mode: host
    depends_on:
      - hyle1
      - hyle2
      - hyle3
      - hyle4

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # Port pour accéder à l'interface de Grafana
    environment:
      - GF_SECURITY_ALLOW_ANONYMOUS_ACCESS=true
    volumes:
      - ./observability/grafana-datasources:/etc/grafana/provisioning/datasources # Montée de volume pour la source de données
    network_mode: host
    depends_on:
      - prometheus
