name: Generate GitHub Release

permissions:
  contents: write
  packages: write
  pull-requests: write

on:
  push:
    tags:
      - '*'

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0

      - name: Get tags
        run: git fetch --tags origin

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Generate release notes
        run: node .github/generateReleaseNotes.js

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_NOTES.md

  bump-version:
    runs-on: ubuntu-latest 
    name: Bump version
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.HYLE_GH_APP_ID }}
          private-key: ${{ secrets.HYLE_GH_APP_SECRET }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: "Write cargo.toml"
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          # Strip 'v' from NEW_VERSION if it starts with it
          CLEAN_VERSION=$(echo "$VERSION" | sed 's/^v//')
          sed -i "s/^version = \".*\"$/version = \"$CLEAN_VERSION\"/" Cargo.toml
          cargo update hyle
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "🔖 Bump version to ${VERSION}" 

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.app-token.outputs.token }}
