name: Generate GitHub Release

permissions:
  contents: write
  packages: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*.*'

jobs:
  generate-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0

      - name: Get tags
        run: git fetch --tags origin

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Generate release notes
        run: node .github/generateReleaseNotes.js

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: "${{ contains(github.ref_name, 'rc') }}"
          body_path: RELEASE_NOTES.md

  publish-crates:
    name: Publish crates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Publish crates 
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p hyle-model
          cargo publish -p hyle-bonsai-runner
          cargo publish -p hyle-contract-sdk
          cargo publish -p hyle-client-sdk
          cargo publish -p hyle-hyllar
          cargo publish -p hyle-hydentity
          cargo publish -p hyle-amm
