name: Run Turmoil Tests

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  test-turmoil:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Run turmoil tests
        run: cargo test turmoil_ --features turmoil
